import { onMessage } from "./messaging";

type NetEntry={url:string;method:string;status:number;type:string;time:number;error?:string};
const network=new Map<number,NetEntry[]>();
function addNetwork(tabId:number,e:NetEntry){const a=network.get(tabId)??[];a.push(e);if(a.length>500)a.shift();network.set(tabId,a);}
chrome.webRequest.onCompleted.addListener(d=>addNetwork(d.tabId,{url:d.url,method:d.method,status:d.statusCode,type:d.type,time:Date.now()}),{urls:["http://*/*","https://*/*"]});
chrome.webRequest.onErrorOccurred.addListener(d=>addNetwork(d.tabId,{url:d.url,method:d.method,status:0,type:d.type,time:Date.now(),error:d.error}),{urls:["http://*/*","https://*/*"]});
chrome.runtime.onInstalled.addListener(()=>chrome.storage.local.set({installed:true,version:chrome.runtime.getManifest().version}));
chrome.action.onClicked.addListener(async tab=>{if(!tab.id)return;await chrome.windows.create({url:chrome.runtime.getURL(`ui/devtools.html?tabId=${tab.id}`),type:"popup",width:1400,height:900,focused:true});});
async function page(tabId:number,msg:unknown){try{return await chrome.tabs.sendMessage(tabId,msg);}catch{try{await chrome.scripting.executeScript({target:{tabId},files:["dist/content.js"]});return await chrome.tabs.sendMessage(tabId,msg);}catch(e){return{error:String(e)};}}}
async function hookConsole(tabId:number){try{await chrome.scripting.executeScript({target:{tabId},world:"MAIN",func:()=>{const w=window as any;if(w.__DEVTOOLSUB_HOOKED)return;w.__DEVTOOLSUB_HOOKED=true;w.__DEVTOOLSUB_CONSOLE=[];for(const level of ["log","info","warn","error","debug"]){const original=(console as any)[level];(console as any)[level]=(...args:any[])=>{w.__DEVTOOLSUB_CONSOLE.push({level,args:args.map(x=>{try{return typeof x==="string"?x:JSON.parse(JSON.stringify(x));}catch{return String(x);}}),time:Date.now()});if(w.__DEVTOOLSUB_CONSOLE.length>300)w.__DEVTOOLSUB_CONSOLE.shift();original.apply(console,args);};}}});return true;}catch{return false;}}
async function readConsole(tabId:number){try{const r=await chrome.scripting.executeScript({target:{tabId},world:"MAIN",func:()=> (window as any).__DEVTOOLSUB_CONSOLE??[]});return r[0]?.result??[];}catch(e){return[{level:"error",args:[String(e)]}];}}
onMessage(async m=>{if(m.type==="active-tab")return(await chrome.tabs.query({active:true,currentWindow:true}))[0];if(m.type==="page-info")return page(Number(m.payload),{type:"collect"});if(m.type==="inspect")return page(Number(m.tabId),{type:"select",payload:Number(m.index)});if(m.type==="computed")return page(Number(m.tabId),{type:"computed"});if(m.type==="layout")return page(Number(m.tabId),{type:"layout"});if(m.type==="hover")return page(Number(m.tabId),{type:"hover",payload:Boolean(m.enabled)});if(m.type==="add-class")return page(Number(m.tabId),{type:"add-class",payload:String(m.name)});if(m.type==="add-style")return page(Number(m.tabId),{type:"add-style",payload:m.payload});if(m.type==="network")return network.get(Number(m.tabId))??[];if(m.type==="console-install")return hookConsole(Number(m.tabId));if(m.type==="console-read")return readConsole(Number(m.tabId));return null;});
