import { onMessage } from "./messaging";
type ElementInfo={index:number;tag:string;id:string;className:string;text:string;style:Record<string,string>;rect:{x:number;y:number;width:number;height:number};events:string[]};
let selected:Element|null=null;
let contextSelected:Element|null=null;
function info(el:Element,index:number):ElementInfo{const h=el as HTMLElement;const s=getComputedStyle(el);const style:Record<string,string>={};for(const n of ["display","position","width","height","margin","padding","color","background-color","font-size","font-family","border","box-sizing","overflow"])style[n]=s.getPropertyValue(n);const eventNames=["onclick","oninput","onchange","onsubmit","onkeydown","onkeyup","onmouseover","onmouseenter","onmouseleave","onfocus","onblur"];return{index,tag:el.tagName.toLowerCase(),id:h.id||"",className:typeof h.className==="string"?h.className:"",text:(h.textContent||"").trim().replace(/\s+/g," ").slice(0,160),style,rect:(()=>{const r=el.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height};})(),events:eventNames.filter(n=>typeof (el as any)[n]==="function")};}
function indexOf(el:Element){return [...document.querySelectorAll("*")].indexOf(el);}
function rules(sheet:CSSStyleSheet){try{return[...sheet.cssRules].slice(0,500).map(r=>r.cssText);}catch{return["Rules unavailable for this stylesheet due to browser origin restrictions."];}}
function mixed(){return location.protocol==="https:"&&[...document.querySelectorAll("img,script,iframe,link,video,audio")].some(e=>((e as HTMLImageElement).src||(e as HTMLLinkElement).href||"").startsWith("http://"));}
function collect(){const all=[...document.querySelectorAll("*")].slice(0,1500);return{title:document.title,url:location.href,origin:location.origin,readyState:document.readyState,html:document.documentElement.outerHTML,htmlLength:document.documentElement.outerHTML.length,elements:all.map((e,i)=>info(e,i)),stylesheets:[...document.styleSheets].map(s=>({href:s.href||"inline",rules:rules(s)})),scripts:[...document.scripts].map(s=>s.src||"inline script"),links:[...document.querySelectorAll<HTMLLinkElement>("link[href]")].map(l=>l.href),images:[...document.images].slice(0,200).map(i=>({src:i.currentSrc||i.src,alt:i.alt})),viewport:{width:innerWidth,height:innerHeight,devicePixelRatio},security:{https:location.protocol==="https:",mixedContent:mixed()}};}
function select(i:number){selected=document.querySelectorAll("*").item(i)||null;return selected?info(selected,i):null;}
function contextSelect(){if(!contextSelected)return null;const i=indexOf(contextSelected);if(i<0)return null;selected=contextSelected;return info(contextSelected,i);}
function computed(){if(!selected)return null;const s=getComputedStyle(selected);const o:Record<string,string>={};for(let i=0;i<s.length;i++){const p=s.item(i);o[p]=s.getPropertyValue(p);}return o;}
function layout(){if(!selected)return null;const r=selected.getBoundingClientRect(),s=getComputedStyle(selected);return{content:{width:r.width,height:r.height},margin:{top:s.marginTop,right:s.marginRight,bottom:s.marginBottom,left:s.marginLeft},padding:{top:s.paddingTop,right:s.paddingRight,bottom:s.paddingBottom,left:s.paddingLeft},border:{top:s.borderTopWidth,right:s.borderRightWidth,bottom:s.borderBottomWidth,left:s.borderBorderBottomWidth},boxSizing:s.boxSizing};}
function hover(on:boolean){if(selected)selected.classList.toggle("__devtoolsub_hover",on);}
function addClass(name:string){if(selected&&/^[A-Za-z_][\w-]*$/.test(name))selected.classList.add(name);}
function addStyle(property:string,value:string){if(selected&&/^[a-z-]+$/i.test(property))(selected as HTMLElement).style.setProperty(property,value);}
onMessage(async m=>{if(m.type==="collect")return collect();if(m.type==="select")return select(Number(m.payload));if(m.type==="context-select")return contextSelect();if(m.type==="computed")return computed();if(m.type==="layout")return layout();if(m.type==="hover"){hover(Boolean(m.payload));return true;}if(m.type==="add-class"){addClass(String(m.payload));return true;}if(m.type==="add-style"){const p=m.payload as {property:string;value:string};addStyle(p.property,p.value);return true;}return null;});
document.addEventListener("contextmenu",event=>{const target=event.target;if(target instanceof Element)contextSelected=target;},true);
const st=document.createElement("style");st.textContent=".__devtoolsub_hover{outline:2px solid #1a73e8!important;outline-offset:2px!important}";document.documentElement.append(st);
